962:0Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 137, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/buildbot/steps/source/base.py", line 228, in start
    self.startVC(branch, revision, patch)
  File "/usr/lib/python2.7/site-packages/buildbot/steps/source/repo.py", line 214, in startVC
    d = self.doStartVC()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1213, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1070, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/site-packages/buildbot/steps/source/repo.py", line 220, in doStartVC
    self.stdio_log = self.addLogForRemoteCommands("stdio")
exceptions.AttributeError: 'Repo' object has no attribute 'addLogForRemoteCommands'
,